name = "cf-worker-ws-dev"
main = "_workerupdate.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "47.245.123.134:443"
UUID = "d1f47a86-3823-4043-a49c-2972795fe1f5"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
